import featherAlertTriangle from "@iconify-icons/feather/alert-triangle";
import featherAlignCenter from "@iconify-icons/feather/align-center";
import featherAlignLeft from "@iconify-icons/feather/align-left";
import featherAlignRight from "@iconify-icons/feather/align-right";
import featherArrowDown from "@iconify-icons/feather/arrow-down";
import featherArrowDownLeft from "@iconify-icons/feather/arrow-down-left";
import featherArrowDownRight from "@iconify-icons/feather/arrow-down-right";
import featherArrowLeft from "@iconify-icons/feather/arrow-left";
import featherArrowRight from "@iconify-icons/feather/arrow-right";
import featherArrowUp from "@iconify-icons/feather/arrow-up";
import featherArrowUpLeft from "@iconify-icons/feather/arrow-up-left";
import featherArrowUpRight from "@iconify-icons/feather/arrow-up-right";
import featherBookmark from "@iconify-icons/feather/bookmark";
import featherCheck from "@iconify-icons/feather/check";
import featherCheckCircle from "@iconify-icons/feather/check-circle";
import featherCircle from "@iconify-icons/feather/circle";
import featherClipboard from "@iconify-icons/feather/clipboard";
import featherCloud from "@iconify-icons/feather/cloud";
import featherCloudLightning from "@iconify-icons/feather/cloud-lightning";
import featherCloudRain from "@iconify-icons/feather/cloud-rain";
import featherCloudSnow from "@iconify-icons/feather/cloud-snow";
import featherCode from "@iconify-icons/feather/code";
import featherCrosshair from "@iconify-icons/feather/crosshair";
import featherEdit from "@iconify-icons/feather/edit";
import featherEdit3 from "@iconify-icons/feather/edit-3";
import featherEye from "@iconify-icons/feather/eye";
import featherEyeOff from "@iconify-icons/feather/eye-off";
import featherFolder from "@iconify-icons/feather/folder";
import featherMaximize2 from "@iconify-icons/feather/maximize-2";
import featherMinimize2 from "@iconify-icons/feather/minimize-2";
import featherMinus from "@iconify-icons/feather/minus";
import featherMoreVertical from "@iconify-icons/feather/more-vertical";
import featherMove from "@iconify-icons/feather/move";
import featherNavigation from "@iconify-icons/feather/navigation";
import featherPause from "@iconify-icons/feather/pause";
import featherPlay from "@iconify-icons/feather/play";
import featherPlus from "@iconify-icons/feather/plus";
import featherRotateCcw from "@iconify-icons/feather/rotate-ccw";
import featherSearch from "@iconify-icons/feather/search";
import featherSettings from "@iconify-icons/feather/settings";
import featherSun from "@iconify-icons/feather/sun";
import featherTag from "@iconify-icons/feather/tag";
import featherTrash2 from "@iconify-icons/feather/trash-2";
import featherX from "@iconify-icons/feather/x";
import featherZap from "@iconify-icons/feather/zap";

import type { IconifyIconData } from "./types";

export const bundledIcons: Map<string, IconifyIconData> = new Map();

bundledIcons.set("feather:settings", featherSettings);
bundledIcons.set("feather:alert-triangle", featherAlertTriangle);
bundledIcons.set("feather:zap", featherZap);
bundledIcons.set("feather:eye", featherEye);
bundledIcons.set("feather:eye-off", featherEyeOff);
bundledIcons.set("feather:maximize-2", featherMaximize2);
bundledIcons.set("feather:minimize-2", featherMinimize2);
bundledIcons.set("feather:arrow-up", featherArrowUp);
bundledIcons.set("feather:arrow-down", featherArrowDown);
bundledIcons.set("feather:arrow-left", featherArrowLeft);
bundledIcons.set("feather:arrow-right", featherArrowRight);
bundledIcons.set("feather:arrow-up-left", featherArrowUpLeft);
bundledIcons.set("feather:arrow-up-right", featherArrowUpRight);
bundledIcons.set("feather:arrow-down-left", featherArrowDownLeft);
bundledIcons.set("feather:arrow-down-right", featherArrowDownRight);
bundledIcons.set("feather:check", featherCheck);
bundledIcons.set("feather:check-circle", featherCheckCircle);
bundledIcons.set("feather:circle", featherCircle);
bundledIcons.set("feather:plus", featherPlus);
bundledIcons.set("feather:minus", featherMinus);
bundledIcons.set("feather:trash-2", featherTrash2);
bundledIcons.set("feather:edit", featherEdit);
bundledIcons.set("feather:edit-3", featherEdit3);
bundledIcons.set("feather:search", featherSearch);
bundledIcons.set("feather:rotate-ccw", featherRotateCcw);
bundledIcons.set("feather:more-vertical", featherMoreVertical);
bundledIcons.set("feather:move", featherMove);
bundledIcons.set("feather:crosshair", featherCrosshair);
bundledIcons.set("feather:x", featherX);
bundledIcons.set("feather:clipboard", featherClipboard);
bundledIcons.set("feather:folder", featherFolder);
bundledIcons.set("feather:bookmark", featherBookmark);
bundledIcons.set("feather:navigation", featherNavigation);
bundledIcons.set("feather:play", featherPlay);
bundledIcons.set("feather:pause", featherPause);
bundledIcons.set("feather:tag", featherTag);
bundledIcons.set("feather:code", featherCode);
bundledIcons.set("feather:sun", featherSun);
bundledIcons.set("feather:cloud", featherCloud);
bundledIcons.set("feather:cloud-rain", featherCloudRain);
bundledIcons.set("feather:cloud-snow", featherCloudSnow);
bundledIcons.set("feather:cloud-lightning", featherCloudLightning);
bundledIcons.set("feather:align-left", featherAlignLeft);
bundledIcons.set("feather:align-center", featherAlignCenter);
bundledIcons.set("feather:align-right", featherAlignRight);
