name: Manual Firefox Signing

on:
  workflow_dispatch:

jobs:
  sign:
    name: Sign Firefox Extension
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Firefox Signing Script
        run: pnpm run sign:firefox
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WEB_EXT_API_KEY: ${{ secrets.AMO_ISSUER }}
          WEB_EXT_API_SECRET: ${{ secrets.AMO_SECRET }}
          GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}
          UNSPLASH_API_KEY: ${{ secrets.UNSPLASH_API_KEY }}
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
          TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
