name: Push

on: push

jobs:
  test:
    uses: ./.github/workflows/_test.yml

  build:
    uses: ./.github/workflows/_build.yml
    secrets: inherit

  deploy:
    name: Deploy to GitHub Pages
    needs: [build]
    if: github.ref == 'refs/heads/main' # Only deploy on main branch
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download web artifact
        uses: actions/download-artifact@v7
        with:
          name: tabliss-web
          path: combined-dist

      - name: Download docs artifact
        uses: actions/download-artifact@v7
        with:
          name: tabliss-docs
          path: combined-dist/docs

      - name: Upload combined artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: combined-dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
